apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-monolith-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osrm-monolith
  template:
    metadata:
      labels:
        app: osrm-monolith
    spec:
      containers:
      - name: osrm-monolith-container
        image: gghotdog/osrm-generator:siberia-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: api-port
        resources:
          limits:
            memory: "6Gi"
        # Лимит можно оставить 2, или немного уменьшить до 1.5
            cpu: "1.5"
          requests:
            memory: "4Gi" # Запрос по памяти пока оставим, проблема была с CPU
        # --- ИЗМЕНЕНИЕ ЗДЕСЬ ---
        # Уменьшаем запрос с "1" до "500m" (половина ядра)
            cpu: "500m"
